[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "__ONRAMP_PROJECT_NAME__"
version = "0.1.0"
description = "An OnRamp __ONRAMP_PROJECT_KIND__ application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "onramp~=__ONRAMP_VERSION__",
]

[tool.setuptools.packages.find]
include = ["app*"]

[tool.aerich]
tortoise_orm = "app.db.db_config.TORTOISE_ORM"
location = "./app/db/migrations"
src_folder = "./."
